### PR TITLE
Add some local minima/maxima searchers

### PR DESCRIPTION
**Pull request by mattwthompson**
As far as I can tell, numpy doesn't have simple built-in functions to do this. The main user-facing functions here should be `find_local_maxima` and `find_local_minima`, which take in RDF data and a starting point from which the nearest local min/max will be searched for. For example, the three dots on this O-O water RDF correspond to separate calls to `find_local_maxima`:

image

### CODE REVIEW

**Comment by mattwthompson** [comment]
Okay, I cleaned this up a bit more, and added an example that generates the following plot, showing the obvious mins and maxes:

image

@rmatsum836 when you get a chance can you give this a once-over?

**Comment by rmatsum836** [comment]
I think in Scipy you can use the `argrelextrema` function: https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.argrelextrema.html.

But taking a look at it now.

**Comment by rmatsum836** [comment]
This is an extremely unlikely edge case, but if you pass the array `np.array([1,1,1,2,3,4,5])` into `find_all_minima` or `find_all_maxima`, an empty array will be returned as these functions can't recognize consecutive local extrema.  However it does work for `np.array([1,2,3,1,4,5])` as it will return `array([0,3])` for local minima.

**Comment by mattwthompson** [comment]
Good find - maybe if that came up in my google searches I wouldn't have spent time writing this.

For that specific case, which isn't too wild, `argrelextrema` doesn't find it either.

```
>>> find_all_maxima(x)
array([6])
>>> find_all_minima(x)
array([], dtype=int64)
>>> argrelextrema(x, np.greater)
(array([], dtype=int64),)
>>> argrelextrema(x, np.less)
(array([], dtype=int64),)
```

We'll just have to be careful when using this; hopefully we'll have reasonable guesses and curves that aren't numerically flat over large regions.

**Pull request merged**
