### PR TITLE
Add other normalization factor for s(q)

### PR DESCRIPTION
**Pull request by rmatsum836**
TRAVIS includes two normalization factors for the structure factor.  This PR adds the normalization factor in equation 4 of DOI: 10.1002/cphc.201500473.

### CODE REVIEW

**Comment by rmatsum836** [comment]
I believe I have the other normalization working. Still need to:

- [ ] Clean up code in `scattering.py`
- [ ] Add unit tests to cover both normalization cases

**Comment by rmatsum836** [comment]
image

I contacted the lead developer of TRAVIS and identified a bug in how the structure factors are written out to CSV format.  By manually fixing the bug, the Faber-Ziman and Ashcroft-Langreth structure factors in this package show much closer agreement with TRAVIS.

This bug fix should be included in the next version of TRAVIS.

**Review by jacoblumpkins — COMMENTED** [review]
In in input check on line 60, the error message says only 'fz' is supported, but the if statement accepts 'fz' and 'al'. On line 128 of the original, partial_sq has a +1 that is not present in the new version at line 125. I don't know if this is intended or not. Otherwise, it looks good to me.

**Comment by rmatsum836** [comment]
> In the input check on line 60, the error message says only 'fz' is supported, but the if statement accepts 'fz' and 'al'. On line 128 of the original, partial_sq has a +1 that is not present in the new version at line 125. I don't know if this is intended or not. Otherwise, it looks good to me.

Yes, I removed the `+1` so that the output of these functions is identical to that of another analysis package.

**Review by jacoblumpkins — APPROVED** [review]

**Comment by rmatsum836** [comment]
Tests are passing locally, will merge once CI has passed.

**Pull request merged**
